//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMS.Migration.MigrateDataService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MigrateDataService.MigrateDataSoap")]
    public interface MigrateDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMissingPages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllMissingPages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMissingPages", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllMissingPagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPayPerClickCombinations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllPayPerClickCombinations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPayPerClickCombinations", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllPayPerClickCombinationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBranchesDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllBranchesDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBranchesDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllBranchesDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLocationsPages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllLocationsPages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllLocationsPages", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllLocationsPagesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MigrateDataSoapChannel : AMS.Migration.MigrateDataService.MigrateDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MigrateDataSoapClient : System.ServiceModel.ClientBase<AMS.Migration.MigrateDataService.MigrateDataSoap>, AMS.Migration.MigrateDataService.MigrateDataSoap {
        
        public MigrateDataSoapClient() {
        }
        
        public MigrateDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MigrateDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MigrateDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MigrateDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllMissingPages() {
            return base.Channel.GetAllMissingPages();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllMissingPagesAsync() {
            return base.Channel.GetAllMissingPagesAsync();
        }
        
        public System.Data.DataTable GetAllPayPerClickCombinations() {
            return base.Channel.GetAllPayPerClickCombinations();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllPayPerClickCombinationsAsync() {
            return base.Channel.GetAllPayPerClickCombinationsAsync();
        }
        
        public System.Data.DataTable GetAllBranchesDetails() {
            return base.Channel.GetAllBranchesDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllBranchesDetailsAsync() {
            return base.Channel.GetAllBranchesDetailsAsync();
        }
        
        public System.Data.DataTable GetAllLocationsPages() {
            return base.Channel.GetAllLocationsPages();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllLocationsPagesAsync() {
            return base.Channel.GetAllLocationsPagesAsync();
        }
    }
}
